//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiLatestUpdate
    {
        public string ApiName { get; set; }
        public string MethodName { get; set; }
        public int CurrentPages { get; set; }
        public int TotalPages { get; set; }
    }
}
