//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpMovie
    {
        public int ID { get; set; }
        public string MovieEngName { get; set; }
        public string MovieLocalName { get; set; }
        public string ReleaseYear { get; set; }
        public string imdbID { get; set; }
        public string MovieType { get; set; }
        public string Poster { get; set; }
    }
}
